/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contactmanagementsoftware;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author ritz619
 */
public class MUI extends javax.swing.JFrame {

    /**
     * Creates new form MUI
     */
    private MUI mg;
    private ArrayList<ArrayList<Acquaintances>> a;
    private AcquaintancesSystem ac;

    private AcquaintancesSystem temp;
    private int x;
    private int num;

    private String op;
    private String str;
//    private ArrayList<JTextComponent> acquaintanceFormComponent = new ArrayList<>();
//    private Manager manager;
    private AcquaintancesFactory acqFactory;

    private PanelState currentPanelState;
    private PanelState addState;
    private PanelState editState;
    private PanelState displayState;
    private PanelState voidState;

    public void setMg(MUI mg) {
        this.mg = mg;
    }

    public void setA(ArrayList<ArrayList<Acquaintances>> a) {
        this.a = a;
    }

    public void setAc(AcquaintancesSystem ac) {
        this.ac = ac;
    }

    private void setFormFieldEditable(boolean b) {
        nameField.setEditable(b);
        mobileField.setEditable(b);
        emailField.setEditable(b);
        otherInformationField1.setEditable(b);
        otherInformationField2.setEditable(b);
        otherInformationField3.setEditable(b);
    }

    private void setFormFieldVisibility(boolean bOtherInformationField1, boolean bOtherInformationField2, boolean bOtherInformationField3) {
        otherInformationField1.setVisible(bOtherInformationField1);
        otherInformationField2.setVisible(bOtherInformationField2);
        otherInformationField3.setVisible(bOtherInformationField3);
    }

    public void setDescription() {
        currentPanelState.setDescription();
    }

    public MUI() {
        initComponents();
        String[] columnNames = {"S.No", "Name", "Mobile", " Email"};
        DefaultTableModel model = new DefaultTableModel(null, columnNames);
        jXTableDetialsDisplay.setModel(model);
        setUpTableData();

        //set up all the state
        editState = new EditState(this);
        addState = new AddState(this);
        displayState = new DisplayState(this);
        voidState = new VoidState(this);
        currentPanelState = voidState;
        acqFactory = new AcquaintancesFactory();
    }

    public final void setUpTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) jXTableDetialsDisplay.getModel();
        tableModel.setRowCount(0);
        ArrayList<AcquaintancesSystem> acList;
        try {
            acList = ac.getAcquaintances(jListAcquaintancesCatagory.getSelectedIndex()).getChild();
        } catch (Exception e) {
            return;
        }

        for (int i = 0; i < acList.size(); i++) {
            String[] data = new String[4];
            HashMap<String, String> acqData = acList.get(i).getInformation();
            data[0] = Integer.toString(i + 1);
            data[1] = acqData.get("Name");
            data[2] = acqData.get("Mobile");
            data[3] = acqData.get("Email");
            tableModel.addRow(data);
        }
        jXTableDetialsDisplay.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainPage = new javax.swing.JPanel();
        jLabelSystemName = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAcquaintancesCatagory = new javax.swing.JList();
        jScrollPaneDetailsDisplay = new javax.swing.JScrollPane();
        jXTableDetialsDisplay = new org.jdesktop.swingx.JXTable();
        jLabelSelectCategoryTitle = new javax.swing.JLabel();
        jLabelDetailsTableTitle = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonViewFullDetail = new javax.swing.JButton();
        jButtonReadFromFile = new javax.swing.JButton();
        jButtonSaveAsFile = new javax.swing.JButton();
        jPanelSearchResult = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextPane();
        jButtonBackToMainMenu = new javax.swing.JButton();
        jPanelDetailsForm = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelMobile = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelOtherInformation1 = new javax.swing.JLabel();
        jLabel8OtherInformation2 = new javax.swing.JLabel();
        jLabelOtherInformation3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        otherInformationField2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        otherInformationField3 = new javax.swing.JTextArea();
        jButtonConfirmDetails = new javax.swing.JButton();
        mobileField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        otherInformationField1 = new javax.swing.JTextArea();
        jButtonCancleDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabelSystemName.setFont(new java.awt.Font("Ubuntu Medium", 0, 20)); // NOI18N
        jLabelSystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemName.setText("<html><u>Contact Management System</u></html>");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jListAcquaintancesCatagory.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Personal Friends", "Relatives", "Professional Friends", "Casual Acquaintances" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListAcquaintancesCatagory.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAcquaintancesCatagoryValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListAcquaintancesCatagory);

        jXTableDetialsDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "S.No", "Name", "Mobile No", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDetailsDisplay.setViewportView(jXTableDetialsDisplay);

        jLabelSelectCategoryTitle.setFont(new java.awt.Font("Ubuntu Medium", 0, 17)); // NOI18N
        jLabelSelectCategoryTitle.setText("Select Category:");

        jLabelDetailsTableTitle.setFont(new java.awt.Font("Ubuntu Medium", 0, 17)); // NOI18N
        jLabelDetailsTableTitle.setText("Details:");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonViewFullDetail.setText("View full detail");
        jButtonViewFullDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewFullDetailActionPerformed(evt);
            }
        });

        jButtonReadFromFile.setText("Read from file");
        jButtonReadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadFromFileActionPerformed(evt);
            }
        });

        jButtonSaveAsFile.setText("Save as file");
        jButtonSaveAsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAsFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainPageLayout = new javax.swing.GroupLayout(jPanelMainPage);
        jPanelMainPage.setLayout(jPanelMainPageLayout);
        jPanelMainPageLayout.setHorizontalGroup(
            jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainPageLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMainPageLayout.createSequentialGroup()
                                .addComponent(jButtonViewFullDetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReadFromFile))
                            .addGroup(jPanelMainPageLayout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainPageLayout.createSequentialGroup()
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainPageLayout.createSequentialGroup()
                                .addComponent(jButtonSaveAsFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addComponent(jLabelSystemName)
                    .addGroup(jPanelMainPageLayout.createSequentialGroup()
                        .addComponent(jLabelSelectCategoryTitle)
                        .addGap(59, 59, 59)
                        .addComponent(jLabelDetailsTableTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMainPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneDetailsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelMainPageLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonDelete, jButtonEdit, jButtonExit, jButtonReadFromFile, jButtonSaveAsFile, jButtonSearch, jButtonViewFullDetail});

        jPanelMainPageLayout.setVerticalGroup(
            jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDelete)
                        .addComponent(jButtonAdd))
                    .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearch)
                        .addComponent(jButtonEdit)))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonExit)
                        .addComponent(jButtonSaveAsFile))
                    .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonViewFullDetail)
                        .addComponent(jButtonReadFromFile)))
                .addGap(49, 49, 49)
                .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectCategoryTitle)
                    .addComponent(jLabelDetailsTableTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDetailsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanelMainPage, "card2");

        details.setEditable(false);
        jScrollPane3.setViewportView(details);

        jButtonBackToMainMenu.setText("Back to main menu");
        jButtonBackToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchResultLayout = new javax.swing.GroupLayout(jPanelSearchResult);
        jPanelSearchResult.setLayout(jPanelSearchResultLayout);
        jPanelSearchResultLayout.setHorizontalGroup(
            jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButtonBackToMainMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchResultLayout.setVerticalGroup(
            jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBackToMainMenu)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanelSearchResult, "card3");

        jPanelDetailsForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Casual Acquaintance Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 16))); // NOI18N

        jLabelName.setText("Name:");

        jLabelMobile.setText("Mobile No:");

        jLabelEmail.setText("Email:");

        jLabelOtherInformation1.setText("First meeting time & location:");

        jLabel8OtherInformation2.setText("First meeting CIrcumstances:");

        jLabelOtherInformation3.setText("Other useful information:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        otherInformationField2.setColumns(20);
        otherInformationField2.setRows(5);
        otherInformationField2.setAutoscrolls(false);
        jScrollPane4.setViewportView(otherInformationField2);

        otherInformationField3.setColumns(20);
        otherInformationField3.setRows(5);
        jScrollPane5.setViewportView(otherInformationField3);

        jButtonConfirmDetails.setText("Add");
        jButtonConfirmDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmDetailsActionPerformed(evt);
            }
        });

        otherInformationField1.setColumns(20);
        otherInformationField1.setRows(5);
        jScrollPane6.setViewportView(otherInformationField1);

        jButtonCancleDetails.setText("Cancel");
        jButtonCancleDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancleDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDetailsFormLayout = new javax.swing.GroupLayout(jPanelDetailsForm);
        jPanelDetailsForm.setLayout(jPanelDetailsFormLayout);
        jPanelDetailsFormLayout.setHorizontalGroup(
            jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetailsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOtherInformation3)
                    .addComponent(jLabel8OtherInformation2)
                    .addComponent(jLabelOtherInformation1)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelMobile)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDetailsFormLayout.createSequentialGroup()
                        .addComponent(jButtonConfirmDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancleDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(132, 132, 132)))
                .addContainerGap())
        );
        jPanelDetailsFormLayout.setVerticalGroup(
            jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMobile)
                    .addComponent(mobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOtherInformation1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailsFormLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8OtherInformation2))
                    .addGroup(jPanelDetailsFormLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOtherInformation3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmDetails)
                    .addComponent(jButtonCancleDetails))
                .addGap(3, 3, 3))
        );

        getContentPane().add(jPanelDetailsForm, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jListAcquaintancesCatagory.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(mg, "Select a category!");
            return;
        }
        jPanelMainPage.setVisible(false);
        jPanelDetailsForm.setVisible(true);
        x = index;
        System.out.println(x);

        //using state dp
        currentPanelState.setState(addState);
        setDescription();
    }

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jListAcquaintancesCatagory.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(mg, "Select a category!");
            return;
        }
        int tindex = jXTableDetialsDisplay.getSelectedRow();
        if (tindex < 0) {
            JOptionPane.showMessageDialog(mg, "Select an entry!");
            return;
        }
        int n = JOptionPane.showConfirmDialog(
                mg,
                "Are you sure you want to delete this?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            ac.getAcquaintances(index).removeAcquaintances(tindex);
//            a.get(index).remove(tindex);
            JOptionPane.showMessageDialog(mg, "Successfully Deleted");
            mg.setUpTableData();
        }
    }

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {
        String s = (String) JOptionPane.showInputDialog(
                mg,
                "Enter name: ",
                "Input",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");
        if (s == null) {
            return;
        }
        jPanelMainPage.setVisible(false);
        jPanelSearchResult.setVisible(true);
        str = s;
        details.setContentType("text/html");
        runn();
    }

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jListAcquaintancesCatagoryValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAcquaintancesCatagoryValueChanged
        setUpTableData();
    }//GEN-LAST:event_jListAcquaintancesCatagoryValueChanged

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jListAcquaintancesCatagory.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(mg, "Select a category!");
            return;
        }
        int tindex = jXTableDetialsDisplay.getSelectedRow();
        if (tindex < 0) {
            JOptionPane.showMessageDialog(mg, "Select an entry!");
            return;
        }
        num = tindex;
        x = index;
        currentPanelState.setState(editState);
        setDescription();
        jPanelMainPage.setVisible(false);
        jPanelDetailsForm.setVisible(true);
    }

    private void jButtonViewFullDetailActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jListAcquaintancesCatagory.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(mg, "Select a category!");
            return;
        }
        int tindex = jXTableDetialsDisplay.getSelectedRow();
        if (tindex < 0) {
            JOptionPane.showMessageDialog(mg, "Select an entry!");
            return;
        }
        num = tindex;
        x = index;
        jPanelMainPage.setVisible(false);
        jPanelDetailsForm.setVisible(true);
        //using state dp
        currentPanelState.setState(displayState);
        setDescription();
    }

    public void runn() {
        String s = "<html> <b>Search results:</b><br>Found!<br><br>Acquaintance Details: <br>";
        for (int i = 0; i < ac.getChild().size(); i++) {
            ArrayList<AcquaintancesSystem> acList = ac.getAcquaintances(i).getChild();
            int count = 0;
            for (int j = 0; j < acList.size(); j++) {
                if (acList.get(j).getInformation().get("Name").matches(str)) {
                    count++;
                    if (count == 1) {
                        s = s.concat("<br>" + ac.getAcquaintances(i).getInformation().get("Name") + "<br>");
                    }
                    s = s.concat("Name: " + acList.get(j).getInformation().get("Name") + "<br>");
                    s = s.concat("Mobile No: " + acList.get(j).getInformation().get("Mobile") + "<br>");
                    s = s.concat("Email: " + acList.get(j).getInformation().get("Email") + "<br>");

                    try {
                        HashMap<String, String> otherInfo = acList.get(j).getOtherInformation();
                        for (String key : otherInfo.keySet()) {
                            s = s.concat(key + ": " + acList.get(j).getOtherInformation().get(key) + "<br>");
                        }
                    } catch (Exception e) {
                    }
                    s.concat("<br>");
                }
            }
        }

        if (s.matches("<html> <b>Search results:</b><br>Found!<br><br>Acquaintance Details: <br>")) {
            s = "<html>No result found</html>";
        } else {
            s = s.concat("</html>");
        }
        details.setText(s);
    }

    private void jButtonReadFromFileActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                System.out.println("Trying to deserialize :");
                SerializationUtil util = SerializationUtil.getInstance();
                temp = (AcquaintancesList) util.deserialize(selectedFile);
                System.out.println("Done deserialize");
            } catch (ClassNotFoundException | IOException e) {
                System.out.println("Error: " + e);
                JOptionPane.showMessageDialog(mg, "Error");
                return;
            }
        } else {
            System.out.println("Error: not APPROVE_OPTION");
            return;
        }

        try {
            for (int i = 0; i < 4; i++) {
                ArrayList<AcquaintancesSystem> acList = temp.getChild();
                for (int j = 0; j < acList.get(i).getChild().size(); j++) {
                    ac.getAcquaintances(i).addAcquaintances(temp.getAcquaintances(i).getAcquaintances(j));
                }
            }
        } catch (Exception e) {
            return;
        }
        mg.setUpTableData();
    }

    private void jButtonSaveAsFileActionPerformed(java.awt.event.ActionEvent evt) {
        String fileName = (String) JOptionPane.showInputDialog(
                mg,
                "Enter file name: (*.ser)",
                "Input",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "output.ser");
        if (!validateFileName(fileName)) {
            return;
        }
        System.out.println("Calling saveFile");
        saveFile(fileName);
    }

    private boolean validateFileName(String fileName) {
        if (fileName == null) {
            return false;
        }
        System.out.println("Pass file name not null");
        if (!fileName.endsWith(".ser")) {
            JOptionPane.showMessageDialog(mg, "File name should end with .ser");
            return false;
        }
        System.out.println("Pass file name end with ser");
        File[] fileList = (new File(".")).listFiles((File pathname) -> pathname.getName().endsWith(".ser"));
        for (File f : fileList) {
            if (f.getName().matches(fileName)) {
                int q = JOptionPane.showConfirmDialog(mg, fileName + " already exists:\nAre you sure you want to overwrite?");
                if (q != 0) {
                    System.out.println("Pressed other than confirm button");
                    return false;
                }
            }
        }
        System.out.println("Pass naming");
        return true;
    }

    private void saveFile(String fileName) {
        try {
            System.out.println("Try to Save");
            SerializationUtil util = SerializationUtil.getInstance();
            util.serialize(ac, fileName);
//            SerializationUtil.serialize(a, fileName);
            System.out.println("Save sucessfully");
        } catch (IOException e) {
            System.out.println("Saving Error: " + e);
            return;
        }
        JOptionPane.showMessageDialog(mg, fileName + " saved successfully");
    }

    private void jButtonBackToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToMainMenuActionPerformed
        jPanelSearchResult.setVisible(false);
        jPanelMainPage.setVisible(true);
    }//GEN-LAST:event_jButtonBackToMainMenuActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    public boolean MobileNoChecker(String str) {
        int x;
        if (str.isEmpty() || str.length() < 6 || str.length() > 15) {
            return false;
        }
        for (int j = 0; j < str.length(); j++) {
            x = (int) str.charAt(j);
            if (x < 48 || x > 57) {
                return false;
            }
        }
        return true;
    }

    public boolean validDate(String Date) {
        String pattern = "[0-3][0-9]/[0-1][0-9]/[0-9]{4}";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(Date);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (!m.find()) {
            JOptionPane.showMessageDialog(mg, "Enter a valid date");
            return false;
        } else {
            return true;
        }
    }

    // New Details
    private void jButtonConfirmDetailsActionPerformed(java.awt.event.ActionEvent evt) {
        String name = nameField.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(mg, "Enter a name");
            return;
        }
        String mobile = mobileField.getText();
        if (!MobileNoChecker(mobile)) {
            JOptionPane.showMessageDialog(mg, "Enter a valid mobile number (6-15 digits)");
            return;
        }
        String email = emailField.getText();
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(mg, "Enter a valid email");
            return;
        }

        Acquaintances acq;
        String otherInformation1, otherInformation2, otherInformation3;
        otherInformation1 = otherInformationField1.getText();
        otherInformation2 = otherInformationField2.getText();
        otherInformation3 = otherInformationField3.getText();
        String[] otherInfoArray = {otherInformation1, otherInformation2, otherInformation3};
        switch (x) {
            case 0: //perF
                if (!performOtherInformationFieldCheckingPF(otherInformation1, otherInformation2, otherInformation3)) {
                    return;
                }
                if (getPanelState() instanceof AddState) {
                    acq = createAcquaintancesInstance(AcquaintancesType.PF, name, mobile, email, otherInfoArray);
                    ac.getAcquaintances(x).addAcquaintances(acq);
                } else {
                    acq = (Acquaintances) ac.getAcquaintances(x).getAcquaintances(num);
                    updateAcquaintancesInstance(acq, name, mobile, email, otherInfoArray);
                }
                break;
            case 1: //rel
                if (!performOtherInformationFieldCheckingR(otherInformation1, otherInformation2, otherInformation3)) {
                    return;
                }
                if (getPanelState() instanceof AddState) {
                    acq = createAcquaintancesInstance(AcquaintancesType.R, name, mobile, email, otherInfoArray);
                    ac.getAcquaintances(x).addAcquaintances(acq);
//                    a.get(x).add(acq);
                } else {
//                    acq = a.get(x).get(num);
                    acq = (Acquaintances) ac.getAcquaintances(x).getAcquaintances(num);
                    updateAcquaintancesInstance(acq, name, mobile, email, otherInfoArray);
                }
                break;
            case 2: //proF
                if (!performOtherInformationFieldCheckingPROF(otherInformation1, otherInformation2, otherInformation3)) {
                    return;
                }
                if (getPanelState() instanceof AddState) {
                    acq = createAcquaintancesInstance(AcquaintancesType.PROF, name, mobile, email, otherInfoArray);
                    ac.getAcquaintances(x).addAcquaintances(acq);

                } else {
                    acq = (Acquaintances) ac.getAcquaintances(x).getAcquaintances(num);
                    updateAcquaintancesInstance(acq, name, mobile, email, otherInfoArray);
                }
                break;
            case 3: //ca
                if (!performOtherInformationFieldCheckingCA(otherInformation1, otherInformation2, otherInformation3)) {
                    return;
                }
                if (getPanelState() instanceof AddState) {
                    acq = createAcquaintancesInstance(AcquaintancesType.CA, name, mobile, email, otherInfoArray);
                    ac.getAcquaintances(x).addAcquaintances(acq);

                } else {
                    acq = (Acquaintances) ac.getAcquaintances(x).getAcquaintances(num);
                    updateAcquaintancesInstance(acq, name, mobile, email, otherInfoArray);
                }
                break;
            default:
                break;
        }
        currentPanelState.setState(voidState);
        setDescription();
        jPanelMainPage.setVisible(true);
        jPanelDetailsForm.setVisible(false);
        mg.setUpTableData();
    }

    // Validate before create Acquaintance Instance
    private boolean performOtherInformationFieldCheckingPF(String otherInformation1, String otherInformation2, String otherInformation3) {
        if (otherInformationField1.isVisible()) {
            if (otherInformation1.isEmpty() || otherInformation1.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }

        if (otherInformationField2.isVisible()) {
            if (otherInformation2.isEmpty() || otherInformation2.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }

        if (otherInformationField3.isVisible()) {
            return validDate(otherInformation3);
        }
        return true;
    }

    private boolean performOtherInformationFieldCheckingR(String otherInformation1, String otherInformation2, String otherInformation3) {
        if (otherInformationField1.isVisible()) {
            return validDate(otherInformation1);
        }
        if (otherInformationField2.isVisible()) {
            return validDate(otherInformation2);
        }
        return true;
    }

    private boolean performOtherInformationFieldCheckingPROF(String otherInformation1, String otherInformation2, String otherInformation3) {
        if (otherInformationField1.isVisible()) {
            if (otherInformation1.isEmpty() || otherInformation1.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }
        return true;
    }

    private boolean performOtherInformationFieldCheckingCA(String otherInformation1, String otherInformation2, String otherInformation3) {
        if (otherInformationField1.isVisible()) {
            if (otherInformation1.isEmpty() || otherInformation1.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }

        if (otherInformationField2.isVisible()) {
            if (otherInformation2.isEmpty() || otherInformation2.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }

        if (otherInformationField3.isVisible()) {
            if (otherInformation3.isEmpty() || otherInformation3.length() > 300) {
                JOptionPane.showMessageDialog(mg, "Enter a valid value ( 1 to 300 chars)");
                return false;
            }
        }
        return true;
    }

    private Acquaintances createAcquaintancesInstance(AcquaintancesType type, String name, String mobileNo, String email, String[] othersInfoArray) {
        return acqFactory.createAcquaintances(type, name, mobileNo, email, othersInfoArray);
    }

    private void updateAcquaintancesInstance(Acquaintances acq, String name, String mobile, String email, String[] othersInfoArray) {
        acq.setName(name);
        acq.setMobileNo(mobile);
        acq.setEmail(email);
        acq.setOtherInformations(othersInfoArray);
    }

    private void jButtonCancleDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancleDetailsActionPerformed
        currentPanelState.setState(voidState);
        setDescription();
        jPanelMainPage.setVisible(true);
        jPanelDetailsForm.setVisible(false);
    }//GEN-LAST:event_jButtonCancleDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane details;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBackToMainMenu;
    private javax.swing.JButton jButtonCancleDetails;
    private javax.swing.JButton jButtonConfirmDetails;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReadFromFile;
    private javax.swing.JButton jButtonSaveAsFile;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonViewFullDetail;
    private javax.swing.JLabel jLabel8OtherInformation2;
    private javax.swing.JLabel jLabelDetailsTableTitle;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelOtherInformation1;
    private javax.swing.JLabel jLabelOtherInformation3;
    private javax.swing.JLabel jLabelSelectCategoryTitle;
    private javax.swing.JLabel jLabelSystemName;
    private javax.swing.JList jListAcquaintancesCatagory;
    private javax.swing.JPanel jPanelDetailsForm;
    private javax.swing.JPanel jPanelMainPage;
    private javax.swing.JPanel jPanelSearchResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneDetailsDisplay;
    private org.jdesktop.swingx.JXTable jXTableDetialsDisplay;
    private javax.swing.JTextField mobileField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea otherInformationField1;
    private javax.swing.JTextArea otherInformationField2;
    private javax.swing.JTextArea otherInformationField3;
    // End of variables declaration//GEN-END:variables

    // start of the get methods
    public JTextPane getDetails() {
        return details;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public JButton getJButtonAdd() {
        return jButtonAdd;
    }

    public JButton getJButtonBackToMainMenu() {
        return jButtonBackToMainMenu;
    }

    public JButton getJButtonCancleDetails() {
        return jButtonCancleDetails;
    }

    public JButton getJButtonConfirmDetails() {
        return jButtonConfirmDetails;
    }

    public JButton getJButtonDelete() {
        return jButtonDelete;
    }

    public JButton getJButtonEdit() {
        return jButtonEdit;
    }

    public JButton getJButtonExit() {
        return jButtonExit;
    }

    public JButton getJButtonReadFromFile() {
        return jButtonReadFromFile;
    }

    public JButton getJButtonSaveAsFile() {
        return jButtonSaveAsFile;
    }

    public JButton getJButtonSearch() {
        return jButtonSearch;
    }

    public JButton getJButtonViewFullDetail() {
        return jButtonViewFullDetail;
    }

    public JLabel getJLabel8OtherInformation2() {
        return jLabel8OtherInformation2;
    }

    public JLabel getJLabelDetailsTableTitle() {
        return jLabelDetailsTableTitle;
    }

    public JLabel getJLabelEmail() {
        return jLabelEmail;
    }

    public JLabel getJLabelName() {
        return jLabelName;
    }

    public JLabel getJLabelMobile() {
        return jLabelMobile;
    }

    public JLabel getJLabelOtherInformation1() {
        return jLabelOtherInformation1;
    }

    public JLabel getJLabelOtherInformation3() {
        return jLabelOtherInformation3;
    }

    public JLabel getJLabelSelectCategoryTitle() {
        return jLabelSelectCategoryTitle;
    }

    public JLabel getJLabelSystemName() {
        return jLabelSystemName;
    }

    public JList getJListAcquaintancesCategory() {
        return jListAcquaintancesCatagory;
    }

    public JPanel getJPanelDetailsForm() {
        return jPanelDetailsForm;
    }

    public JPanel getJPanelMainPage() {
        return jPanelMainPage;
    }

    public JPanel getJPanelSearchResult() {
        return jPanelSearchResult;
    }

    public JScrollPane getJScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getJScrollPane3() {
        return jScrollPane3;
    }

    public JScrollPane getJScrollPane4() {
        return jScrollPane4;
    }

    public JScrollPane getJScrollPane5() {
        return jScrollPane5;
    }

    public JScrollPane getJScrollPane16() {
        return jScrollPane6;
    }

    public JScrollPane getJScrollPaneDetailsDisplay() {
        return jScrollPaneDetailsDisplay;
    }

    public JXTable getJXTableDetialsDisplay() {
        return jXTableDetialsDisplay;
    }

    public JTextField getMobileField() {
        return mobileField;
    }

    public JTextField getNameField() {
        return nameField;
    }

    public JTextArea getOtherInformationField1() {
        return otherInformationField1;
    }

    public JTextArea getOtherInformationField2() {
        return otherInformationField2;
    }

    public JTextArea getOtherInformationField3() {
        return otherInformationField3;
    }

    public String getOp() {
        return op;
    }

    public ArrayList<ArrayList<Acquaintances>> getA() {
        return a;
    }
    
    public AcquaintancesSystem getAc(){
        return ac;
    }

    public int getNum() {
        return num;
    }

    public int getX() {
        return x;
    }

    public void setPanelState(PanelState state) {
        currentPanelState = state;
    }

    public PanelState getPanelState() {
        return currentPanelState;
    }
}
